---
locale: en-US
title: Robbie Maris
title_separator: ""
name: Robbie Maris
description: Hello - I am cool.
url: https://robbie-maris.github.io
baseurl: ""
repository: robbie-maris/robbie-maris.github.io
author:
  avatar: profile-pic1.png
  name: Robbie Maris
  pronouns: He/Him
  bio: Economics of Education PhD Student
  location: London, UK
  employer: University College London
  uri: null
  email: robert.maris.23@ucl.ac.uk
  arxiv: null
  googlescholar: https://scholar.google.com/citations?user=wgOQC80AAAAJ&hl=en
  impactstory: null
  orcid: https://orcid.org/0000-0001-9845-4606
  semantic: null
  pubmed: null
  researchgate: null
  bitbucket: null
  codepen: null
  dribbble: null
  github: robbie-maris
  kaggle: null
  stackoverflow: null
  bluesky: null
  facebook: null
  flickr: null
  foursquare: null
  goodreads: null
  google_plus: null
  keybase: null
  instagram: null
  lastfm: null
  linkedin: null
  mastodon: null
  medium: null
  pinterest: null
  soundcloud: null
  steam: null
  telegram: null
  tumblr: null
  twitter: Robbiemaris1
  vine: null
  weibo: null
  wikipedia: null
  xing: null
  youtube: null
  zhihu: null
publication_category:
  books:
    title: Books
  manuscripts:
    title: Journal Articles
  conferences:
    title: Conference Papers
teaser: null
breadcrumbs: false
words_per_minute: 160
future: true
read_more: disabled
talkmap_link: false
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
    - name
    - email
    - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  hide: false
  path: null
google_site_verification: null
bing_site_verification: null
alexa_site_verification: null
yandex_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: "false"
  google:
    tracking_id: null
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: wp
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
timezone: America/Los_Angeles
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
